export const LoginActionTypes = {
  LOGIN_LAODING: "LOGIN_LAODING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT"
};

export const MazeStatsActionTypes = {
  MAZE_STATS_LAODING: "MAZE_STATS_LAODING",
  MAZE_STATS_SUCCESS: "MAZE_STATS_SUCCESS",
  MAZE_STATS_FAILURE: "MAZE_STATS_FAILURE"
};

export const AvatarActionTypes = {
  AVATAR_DATA_LAODING: "AVATAR_DATA_LAODING",
  AVATAR_DATA_SUCCESS: "AVATAR_DATA_SUCCESS",
  AVATAR_DATA_FAILURE: "AVATAR_DATA_FAILURE"
};
